apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cognitiveai

resources:
- namespace.yaml
- configmap.yaml
- backend-deployment.yaml
- frontend-deployment.yaml
- network-policy.yaml

commonLabels:
  app.kubernetes.io/name: cognitiveai
  app.kubernetes.io/instance: production
